import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { getGlobalData } from "@/data/loaders";
import { Header } from "@/components/custom/Header";
import { Footer } from "@/components/custom/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const globalData = await getGlobalData();
  const { header } = globalData.data[0];
  const { footer } = globalData.data[0];
  return (
    <html lang="en">
      <body className="{inter.className}">
        <Header data={header} />
        <div>{children}</div>
        <Footer data={footer} />
      </body>
    </html>
  );
}
